server:
  port: ${CONFIG_SERVER_PORT}
spring:
  application:
    name: config
  config:
    import: optional:file:.env[.properties]
  profiles:
    active: native
  #active: git
  cloud:
    config:
      server:
        native:
          search-locations: file:../StockPin/config/src/main/resources/configfiles/
#        git:
#          uri: ${spring.cloud.config.server.git.uri}
#          username: ${spring.cloud.config.server.git.username}
#          password: ${spring.cloud.config.server.git.password}
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: ${EUREKA_DEFAULT_ZONE}
