server:
  port: ${GATEWAY_SERVER_PORT}
spring:
  config:
    import: optional:file:.env[.properties]
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "lb://Test"
            allow-credentials: true
            allowedHeaders:
              - x-requested-with
              - authorization
              - content-type
              - credential
              - X-AUTH-TOKEN
              - X-CSRF-TOKEN
            allowedMethods:
              - POST
              - GET
              - PUT
              - OPTIONS
              - DELETE

      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: Test
          uri: lb://Test
          predicates:
            - Path=/Test/**
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
    gateway:
      enabled: true

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      #      defaultZone: http://eureka-server:8761/eureka/
      defaultZone: ${EUREKA_DEFAULT_ZONE}
