spring:
  application:
    name: gateway-deploy
  config:
    activate:
      on-profile: deploy
    import:
      - optional:configserver:http://localhost:8888
      - optional:file:.env[.properties]
